#ifdef __MULLE_OBJC__

#import "MulleObjCDeps+MulleThread.h"


@implementation MulleObjCDeps( MulleThread)

//
// The file objc-deps.inc is generated by the mulle-objc-developer
// tool set automatically during a cmake build. Creation of "objc-deps.inc"
// can be turned off in CMakeLists.txt with CREATE_OBJC_LOADER_INC=OFF
//
+ (struct _mulle_objc_dependency *) dependencies
{
   static struct _mulle_objc_dependency   dependencies[] =
   {
#include "objc-deps.inc"

      { MULLE_OBJC_NO_CLASSID, MULLE_OBJC_NO_CATEGORYID }
   };

   return( dependencies);
}

@end

#endif


/*
 * extension : mulle-objc/objc
 * directory : project-oneshot/library
 * template  : .../MulleObjCDeps+PROJECT_NAME.PROJECT_EXTENSION
 * Suppress this comment with `export MULLE_SDE_GENERATE_FILE_COMMENTS=NO`
 */
