/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_invocation_queue_include_h__
#define _mulle_invocation_queue_include_h__

// You can tweak the following #include with these commands.
// (Use 4ADF2001-2E2E-4B84-9B65-2EF35C84246D instead of mulle-multififo if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-multififo no-header`
//    rename:              `mulle-sde dependency|library set mulle-multififo include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-multififo <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-multififo [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-multififo [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-multififo [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-multififo no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-multififo/mulle-multififo.h>   // mulle-multififo

#endif
