/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 9F92D0CF-8BBA-4F6B-8D14-6A31BC49FB5B instead of MulleObjCLockFoundation if there are duplicate entries)
//    remove #import: : `mulle-sde dependency mark MulleObjCLockFoundation no-header`
//    rename:              `mulle-sde dependency|library set MulleObjCLockFoundation include whatever.h`
//    reorder:             `mulle-sde dependency move MulleObjCLockFoundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleObjCLockFoundation [no-]import`
//    toggle public:       `mulle-sde dependency mark MulleObjCLockFoundation [no-]public`
//    toggle optional:     `mulle-sde dependency mark MulleObjCLockFoundation [no-]require`
//    remove for platform: `mulle-sde dependency mark MulleObjCLockFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleObjCLockFoundation/MulleObjCLockFoundation.h>   // MulleObjCLockFoundation

#ifdef __has_include
# if __has_include( "_MulleInvocationQueue-include.h")
#  include "_MulleInvocationQueue-include.h"
# endif
#endif

