      { @selector( MulleObjCLoader), @selector( MulleObjCLockFoundation) },      // 47a9beb6;MulleObjCLoader;86a97828;MulleObjCLockFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCTimeFoundation) },      // 47a9beb6;MulleObjCLoader;cc20d48b;MulleObjCTimeFoundation
      { @selector( MulleInvocationQueue), MULLE_OBJC_NO_CATEGORYID },      // 9a5137b3;MulleInvocationQueue;;
      { @selector( MulleThread), MULLE_OBJC_NO_CATEGORYID },      // c7c34b28;MulleThread;;
      { @selector( NSInvocation), @selector( MulleReturnStatus) },      // c089c043;NSInvocation;bd6f8a28;MulleReturnStatus
      { @selector( NSInvocation), @selector( UTF8String) },      // c089c043;NSInvocation;0a62c4be;UTF8String
